name: Obfuscate Worker

on:
  workflow_dispatch:     # امکان اجرای دستی
  push:
    paths:
      - worker.js       # فقط وقتی worker.js تغییر کنه اجرا شه

jobs:
  obfuscate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install obfuscator
        run: npm install -g javascript-obfuscator

      - name: Obfuscate worker.js
        run: javascript-obfuscator worker.js --output worker-obfuscated.js

      - name: Commit obfuscated file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add worker-obfuscated.js
          git commit -m "Auto-obfuscate worker.js"
          git push
